--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/ServerUI
build-by-default: true
branches:
- main
projects:
  ServerUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
    version: ^2.0.1
...
