name: ServerUI
main: NurAzliYT\ServerUI\ServerUI
api: 5.0.0
version: 1.0.0
author: NurAzliYT
description: "ServerUI Reward Menu For Your Server"

commands:
ui:
description: "ServerUI Commands"
permission: serverui.command

permissions:
serverui.command:
default: op
